/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.eganjs.gradle.simpleversioning

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
